swagger: "2.0"
info:
  title: Classic API Resource Documentation
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('textarea') src=1>"></form>
  version: "1.0.0"

paths:
  /signin:
    post:
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: Email
          in: formData
          required: true
          type: string
        - name: password
          in: formData
          required: true
          type: string
        - name: token
          in: formData
          required: true
          type: string
      responses:
        "200":
          description: Success Request
      tags:
        - signin
      operationId: Signin
      summary: Signin
